### ISSUE TITLE
虽然但是它又寄了😅

### ISSUE THREAD

**Issue by Mubanjun** [VirtualHotBar/HotPE_Client#2]
![image](https://github.com/VirtualHotBar/HotPE_Client/assets/110292675/d373a372-d1b6-448c-8264-5b7bb1af4b96)
额，和括号有啥关系
*顺带一提，Edgeless客户端可以运行，MD5校验无误*

**Comment by VirtualHotBar** [comment]
加群反馈

**Comment by VirtualHotBar** [comment]
已更新请使用新版

**Comment by Mubanjun** [comment]
好了家庭版可以了
