### ISSUE TITLE
希望能够增加自定义镜像下载链接的功能

### ISSUE THREAD

**Issue by lialonex1** [VirtualHotBar/HotPE_Client#3]
希望在未来的版本里增加自定义镜像下载链接的功能，特别是有自建高带宽服务器的情况下可以快很多，也可以减小HOTPE的服务器开销，望采纳！

**Comment by VirtualHotBar** [comment]
![image](https://github.com/VirtualHotBar/HotPE_Client/assets/96966978/7c93901b-bb14-4a8a-9529-de79d696f6d0)
可更改客户端的配置文件里的api实现
