### ISSUE TITLE
点击更新最新版本后，寄了

### ISSUE THREAD

**Issue by tianmiao8152** [VirtualHotBar/HotPE_Client#4]
![1706873597604](https://github.com/VirtualHotBar/HotPE_Client/assets/83683108/2269ebb6-b10c-4893-bdfd-4b6d3832f29c)
![1706873605621](https://github.com/VirtualHotBar/HotPE_Client/assets/83683108/b3b3bf17-1eb7-413c-a09f-6de256bbc156)

**Comment by VirtualHotBar** [comment]
更新后出现这个问题，删除.\resources\config.json就好了
