### ISSUE TITLE
无法打包

### ISSUE THREAD

**Issue by btwise** [VirtualHotBar/HotPE_Client#5]
使用cnpm run build命令打包报错，提示代码引用错误，如何能正确打包，或者打包成单EXE文件？

**Comment by VirtualHotBar** [comment]
图

**Comment by btwise** [comment]
> 图

package.json里缺少生产模式下app.asar里的的依赖，编译后无法运行，另外建议编译成nsis安装包

**Comment by VirtualHotBar** [comment]
我觉得免安装直接用很好，省去安装步骤
关于依赖，你应该解决了，你没有提供缺少的依赖。我本地可以成功编译

**Comment by btwise** [comment]
@VirtualHotBar 
你老版的pe安装工具箱可以分享一下源码吗？

**Comment by VirtualHotBar** [comment]
不方便给，怕烂大街，怕别人拿去卖钱。不开源对大家都好
